import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireWorkspace } from '@/lib/auth';
import { query } from '@/lib/db';
import SignalCard from '@/components/SignalCard';
import EmptyState from '@/components/EmptyState';

function Chips({items}){const list=Array.isArray(items)?items:[];return list.length?<div className="chip-list">{list.map((x,i)=><span className="intel-chip" key={`${x}-${i}`}>{String(x)}</span>)}</div>:<span className="muted" style={{fontSize:12}}>Insufficient evidence</span>}
function Score({label,value}){const n=Math.max(0,Math.min(100,Number(value)||0));return <div className="score-row"><div><div className="muted" style={{fontSize:10,marginBottom:5}}>{label}</div><div className="score-track"><span style={{width:`${n}%`}}/></div></div><strong className="mono" style={{fontSize:12}}>{n}</strong></div>}

export default async function CompanyDetail({params}){
  const {workspace}=await requireWorkspace();const {id}=await params;
  const company=(await query(`SELECT c.*,cp.*,r.relationship_type,r.status relationship_status,r.similarity,r.threat,r.confidence relationship_confidence,r.score_components,r.rationale FROM companies c LEFT JOIN company_profiles cp ON cp.company_id=c.id LEFT JOIN relationships r ON r.target_company_id=c.id AND r.workspace_id=c.workspace_id WHERE c.id=$1 AND c.workspace_id=$2 LIMIT 1`,[id,workspace.id])).rows[0];
  if(!company)notFound();
  const [signals,sources,evidence]=await Promise.all([
    query(`SELECT s.*,c.name company_name FROM signals s JOIN companies c ON c.id=s.company_id WHERE s.workspace_id=$1 AND s.company_id=$2 ORDER BY s.detected_at DESC LIMIT 20`,[workspace.id,id]),
    query(`SELECT * FROM sources WHERE workspace_id=$1 AND company_id=$2 ORDER BY COALESCE(last_checked_at,created_at) DESC`,[workspace.id,id]),
    query(`SELECT * FROM evidence WHERE workspace_id=$1 AND company_id=$2 ORDER BY retrieved_at DESC LIMIT 12`,[workspace.id,id])
  ]);
  const sim=company.score_components?.similarity||{};const threat=company.score_components?.threat||{};
  return <main className="content"><div className="company-hero"><div><Link href="/dashboard/companies" className="muted" style={{fontSize:11}}>← Competitive universe</Link><div className="eyebrow" style={{marginTop:16}}>COMPANY INTELLIGENCE PROFILE</div><h1 className="page-title" style={{marginBottom:4}}>{company.name}</h1><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><span className={`badge ${company.is_primary?'good':'cyan'}`}>{company.is_primary?'Your startup':String(company.classification||company.relationship_type||'watchlist').replaceAll('_',' ')}</span>{company.website&&<a className="muted" style={{fontSize:11}} href={company.website} target="_blank" rel="noreferrer">{company.domain||company.website} ↗</a>}</div><p className="sub" style={{marginTop:16}}>{company.summary||'RADAR has not collected enough evidence to summarize this company yet.'}</p></div>{!company.is_primary&&<div className="threat-orb"><span>THREAT</span><strong>{company.threat||0}</strong><small>Similarity {company.similarity||0} · Confidence {company.relationship_confidence||company.confidence||0}</small></div>}</div>
  <section className="grid grid-3" style={{marginTop:22}}><div className="card"><div className="eyebrow">MARKET ROLE</div><h2 style={{fontSize:17}}>{company.industry||'Industry unconfirmed'}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6}}>{company.subcategory||company.rationale||'RADAR will refine this as evidence accumulates.'}</p></div><div className="card"><div className="eyebrow">POSITIONING</div><h2 style={{fontSize:17}}>{company.positioning||'Positioning not yet confirmed'}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6}}>{company.messaging||'No stable messaging baseline yet.'}</p></div><div className="card"><div className="eyebrow">PRICING / MODEL</div><h2 style={{fontSize:17}}>{company.pricing||'Pricing unknown'}</h2><p className="muted" style={{fontSize:12,lineHeight:1.6}}>{company.business_model||'Business model not yet confirmed.'}</p></div></section>
  {!company.is_primary&&<section className="card" style={{marginTop:14}}><div className="grid grid-2"><div><div className="eyebrow">SIMILARITY BREAKDOWN</div>{Object.keys(sim).length?Object.entries(sim).map(([k,v])=><Score key={k} label={k.replaceAll('_',' ').toUpperCase()} value={v}/>):<Score label="OVERALL SIMILARITY" value={company.similarity}/>}</div><div><div className="eyebrow">THREAT BREAKDOWN</div>{Object.keys(threat).length?Object.entries(threat).map(([k,v])=><Score key={k} label={k.replaceAll('_',' ').toUpperCase()} value={v}/>):<Score label="OVERALL THREAT" value={company.threat}/>}</div></div>{company.rationale&&<div className="insight-callout"><b>Why RADAR cares</b><span>{company.rationale}</span></div>}</section>}
  <section className="grid grid-2" style={{marginTop:14}}><div className="card"><div className="eyebrow">PRODUCT INTELLIGENCE</div><h3>Products</h3><Chips items={company.products}/><h3>Features</h3><Chips items={company.features}/><h3>Technologies</h3><Chips items={company.technologies}/></div><div className="card"><div className="eyebrow">MARKET FOOTPRINT</div><h3>Target customers</h3><Chips items={company.target_customers}/><h3>Geography</h3><Chips items={company.geography}/><h3>Problem / use case</h3><p className="muted" style={{fontSize:12,lineHeight:1.65}}>{company.problem_use_case||'Insufficient evidence'}</p></div></section>
  <h2 className="section-title">Signal history</h2><div className="card">{signals.rows.length?signals.rows.map(s=><SignalCard signal={s} key={s.id}/>):<EmptyState title="No meaningful changes yet" body="RADAR has not stored a verified strategic event for this company since the baseline was created."/>}</div>
  <section className="grid grid-2" style={{marginTop:14}}><div><h2 className="section-title">Source coverage</h2><div className="card">{sources.rows.length?sources.rows.slice(0,10).map(s=><div className="source-line" key={s.id}><div><span className={`health-dot ${s.health}`}/><strong>{s.title||s.source_type}</strong><div className="muted" style={{fontSize:10,marginTop:3}}>{s.source_type} · every {s.check_frequency_minutes} min</div></div><a className="muted" href={s.url} target="_blank" rel="noreferrer" style={{fontSize:10}}>Source ↗</a></div>):<EmptyState title="No sources yet" body="Approve monitoring or wait for source discovery."/>}</div></div><div><h2 className="section-title">Latest evidence</h2><div className="card">{evidence.rows.length?evidence.rows.slice(0,8).map(e=><div className="source-line" key={e.id}><div><strong>{e.source_title||'Public evidence'}</strong><div className="muted" style={{fontSize:10,marginTop:3}}>Reliability {e.reliability} · {new Date(e.retrieved_at).toLocaleDateString()}</div></div><a className="muted" href={e.source_url} target="_blank" rel="noreferrer" style={{fontSize:10}}>Open ↗</a></div>):<EmptyState title="No evidence yet" body="Evidence appears as RADAR researches this company."/>}<Link className="button ghost" style={{display:'inline-block',marginTop:12}} href={`/dashboard/evidence?company=${company.id}`}>Open evidence vault</Link></div></div></section>
  </main>
}
