'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function DecisionCard({item}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[note,setNote]=useState(item.decided_option||'');const[outcome,setOutcome]=useState(false);const[error,setError]=useState('');
  const rec=item.recommendation&&typeof item.recommendation==='object'?item.recommendation:{};const options=Array.isArray(item.options)?item.options:[];const assumptions=Array.isArray(rec.assumptions)?rec.assumptions:[];
  async function setStatus(status){setBusy(true);setError('');try{const r=await fetch('/api/decisions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({decisionId:item.id,status,decision:note})});const d=await r.json();if(!r.ok)throw new Error(d.error);router.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveOutcome(e){e.preventDefault();setBusy(true);setError('');try{const form=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/outcomes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decisionId:item.id,result:form.result,impact:form.impact?Number(form.impact):null,assessment:form.assessment})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOutcome(false);router.refresh()}catch(e2){setError(e2.message)}finally{setBusy(false)}}
  return <article className="card decision-card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}}><div><div className="eyebrow">{item.move_type?.replaceAll('_',' ')||'STRATEGIC DECISION'} · {item.status}</div><h2 style={{fontSize:20,margin:'7px 0'}}>{item.title}</h2><div className="muted" style={{fontSize:11}}>{item.company_name||'Your company'} · {item.confidence}% confidence</div></div><div className="move-score high">{item.impact_score||item.confidence}</div></div>{item.question&&<p style={{marginTop:12}}><strong>Decision:</strong> {item.question}</p>}{item.context&&<p className="muted" style={{fontSize:12,lineHeight:1.6}}>{item.context}</p>}<div className="move-action" style={{marginTop:14}}><b>RADAR recommendation</b>{rec.summary||'Review the evidence and choose the most reversible response.'}</div>{rec.expected_outcome&&<div className="muted" style={{fontSize:11,marginTop:8}}><b>Expected outcome:</b> {rec.expected_outcome}</div>}{options.length>0&&<div className="decision-options">{options.map((o,i)=><div className="decision-option" key={`${o.label}-${i}`}><strong>{o.label}</strong><p>{o.action}</p><small>Upside: {o.upside}</small><small>Downside: {o.downside}</small>{o.when_to_choose&&<small>Choose when: {o.when_to_choose}</small>}</div>)}</div>}{assumptions.length>0&&<details style={{marginTop:12}}><summary className="muted">Assumptions RADAR is making</summary><ul className="muted" style={{fontSize:11,lineHeight:1.7}}>{assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul></details>}<div className="field" style={{marginTop:12}}><label>Your decision / note</label><textarea className="textarea" rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Record why your team chose this response…"/></div><div className="actions"><button className="button primary" disabled={busy} onClick={()=>setStatus('accepted')}>Accept</button><button className="button" disabled={busy} onClick={()=>setStatus('deferred')}>Defer</button><button className="button" disabled={busy} onClick={()=>setStatus('rejected')}>Reject</button>{['accepted','completed'].includes(item.status)&&<button className="button" type="button" onClick={()=>setOutcome(v=>!v)}>Record outcome</button>}</div>{outcome&&<form className="form" style={{marginTop:14}} onSubmit={saveOutcome}><div className="field"><label>What happened?</label><input className="input" name="result" placeholder="Result of the strategic action" required/></div><div className="field"><label>Impact score (0-100)</label><input className="input" name="impact" type="number" min="0" max="100"/></div><div className="field"><label>What did we learn?</label><textarea className="textarea" rows="3" name="assessment" placeholder="Evidence, surprises, what RADAR should learn…"/></div><button className="button primary" disabled={busy}>Save outcome</button></form>}{error&&<div className="error" style={{marginTop:10}}>{error}</div>}</article>
}
