import { query } from './db.js';
import { id } from './ids.js';
const FALLBACK={companies:3,monitoring_minutes:1440,daily_ai_runs:20,war_room:false,team_members:1};
export async function ensureFreeSubscription(workspaceId){const existing=await query('SELECT 1 FROM subscriptions WHERE workspace_id=$1 LIMIT 1',[workspaceId]);if(!existing.rowCount)await query(`INSERT INTO subscriptions(id,workspace_id,plan_id,status) VALUES($1,$2,'free','active') ON CONFLICT(workspace_id) DO NOTHING`,[id('sub'),workspaceId])}
export async function getWorkspacePlan(workspaceId){const result=await query(`SELECT s.status,s.current_period_end,p.id plan_id,p.name,p.currency,p.monthly_price_minor,p.entitlements FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.workspace_id=$1 LIMIT 1`,[workspaceId]);if(!result.rowCount)return{plan_id:'free',name:'Free',status:'active',entitlements:FALLBACK};const row=result.rows[0];const entitled=row.plan_id==='free'||row.status==='active';if(!entitled)return{...row,effective_plan_id:'free',effective_name:'Free',entitlements:FALLBACK};return{...row,effective_plan_id:row.plan_id,effective_name:row.name,entitlements:row.entitlements||FALLBACK}}
export async function entitlement(workspaceId,key,fallback=null){const plan=await getWorkspacePlan(workspaceId);return plan.entitlements?.[key]??fallback}
export async function recordUsage(workspaceId,eventType,quantity=1,metadata={}){await query(`INSERT INTO usage_events(workspace_id,event_type,quantity,metadata) VALUES($1,$2,$3,$4::jsonb)`,[workspaceId||null,eventType,Number(quantity||1),JSON.stringify(metadata||{})]).catch(()=>{})}
export async function assertAiAllowance(workspaceId){if(!workspaceId||process.env.RADAR_ENFORCE_AI_LIMITS==='false')return true;const limit=Number(await entitlement(workspaceId,'daily_ai_runs',FALLBACK.daily_ai_runs));const used=(await query(`SELECT COALESCE(sum(quantity),0)::int used FROM usage_events WHERE workspace_id=$1 AND event_type='ai_run' AND created_at>=date_trunc('day',now())`,[workspaceId])).rows[0]?.used||0;if(Number(used)>=limit)throw new Error(`Daily AI allowance reached for this workspace (${limit}). Upgrade the plan or wait for the next usage window.`);return true}
export async function assertCompanyLimit(workspaceId){const[limit,countResult]=await Promise.all([entitlement(workspaceId,'companies',FALLBACK.companies),query(`SELECT count(*)::int count FROM companies WHERE workspace_id=$1 AND is_primary=false AND approved_at IS NOT NULL AND status<>'removed'`,[workspaceId])]);if(Number(countResult.rows[0].count)>=Number(limit))throw new Error(`Your current plan supports up to ${limit} monitored companies. Upgrade to add more.`)}
