import { query } from './db.js';
import { runInitialScan, refreshDiscovery, runMarketResearch, generateBriefing } from './intelligence.js';
import { runWorkspaceRefresh } from './monitor.js';
import { syncWatchGraph } from './watchGraph.js';
import { detectMovesForCompany } from './moves.js';
import { enqueue, QUEUES } from './queue.js';

export async function processJob(job){const payload=typeof job.payload==='string'?JSON.parse(job.payload):job.payload||{};const type=payload.type;let result;if(type==='scan.initial'){result=await runInitialScan(payload);await syncWatchGraph(payload.workspaceId).catch(()=>{});}else if(type==='workspace.refresh'){result=await runWorkspaceRefresh(payload.workspaceId);const research=await runMarketResearch(payload.workspaceId).catch(error=>({error:error.message,events:0}));result={...result,liveWebSignals:research.events||0,liveWebError:research.error||null};}else if(type==='market.research'){result=await runMarketResearch(payload.workspaceId);}else if(type==='discovery.refresh'){result=await refreshDiscovery(payload.workspaceId);await syncWatchGraph(payload.workspaceId).catch(()=>{});}else if(type==='briefing.generate'){result=await generateBriefing(payload.workspaceId,payload.period||'daily');}else throw new Error(`Unknown RADAR job type: ${type}`);if(payload.workspaceId){const companies=(await query(`SELECT id FROM companies WHERE workspace_id=$1 AND is_primary=false AND status IN ('active','candidate')`,[payload.workspaceId])).rows;for(const c of companies)await detectMovesForCompany(payload.workspaceId,c.id).catch(()=>{});}return result}

export async function enqueueInitialScan({workspaceId,companyId,scanId}){return enqueue(QUEUES.initialScan,{type:'scan.initial',workspaceId,companyId,scanId},{priority:95})}
export async function enqueueWorkspaceRefresh(workspaceId){return enqueue(QUEUES.workspaceRefresh,{type:'workspace.refresh',workspaceId},{priority:80})}

export async function scheduleRecurringJobs(){const workspaces=(await query('SELECT id FROM workspaces ORDER BY created_at ASC')).rows;for(const w of workspaces){for(const task of [{key:'briefing.daily',minutes:1440,queue:QUEUES.briefings,payload:{type:'briefing.generate',workspaceId:w.id,period:'daily'}},{key:'briefing.weekly',minutes:10080,queue:QUEUES.briefings,payload:{type:'briefing.generate',workspaceId:w.id,period:'weekly'}},{key:'discovery.refresh',minutes:720,queue:QUEUES.discovery,payload:{type:'discovery.refresh',workspaceId:w.id}},{key:'market.research',minutes:Math.max(30,Number(process.env.MARKET_RESEARCH_INTERVAL_MINUTES||240)),queue:QUEUES.marketResearch,payload:{type:'market.research',workspaceId:w.id}}]){await query(`INSERT INTO recurring_tasks(workspace_id,task_key,interval_minutes,next_run_at) VALUES($1,$2,$3,now()+($3::text||' minutes')::interval) ON CONFLICT(workspace_id,task_key) DO UPDATE SET interval_minutes=EXCLUDED.interval_minutes`,[w.id,task.key,task.minutes])}}
const due=(await query(`SELECT workspace_id,task_key,interval_minutes FROM recurring_tasks WHERE next_run_at<=now() AND (queued_at IS NULL OR queued_at<now()-interval '30 minutes') ORDER BY next_run_at ASC LIMIT 100`)).rows;let enqueued=0;for(const row of due){const map={'briefing.daily':[QUEUES.briefings,{type:'briefing.generate',workspaceId:row.workspace_id,period:'daily'}],'briefing.weekly':[QUEUES.briefings,{type:'briefing.generate',workspaceId:row.workspace_id,period:'weekly'}],'discovery.refresh':[QUEUES.discovery,{type:'discovery.refresh',workspaceId:row.workspace_id}],'market.research':[QUEUES.marketResearch,{type:'market.research',workspaceId:row.workspace_id}]};const spec=map[row.task_key];if(!spec)continue;const claimed=await query(`UPDATE recurring_tasks SET queued_at=now(),next_run_at=now()+(interval_minutes::text||' minutes')::interval,updated_at=now() WHERE workspace_id=$1 AND task_key=$2 AND (queued_at IS NULL OR queued_at<now()-interval '30 minutes') RETURNING task_key`,[row.workspace_id,row.task_key]);if(!claimed.rowCount)continue;await enqueue(spec[0],spec[1]);enqueued++}return enqueued}
