import { query } from './db.js';
import { id } from './ids.js';
import { unseal } from './cryptoBox.js';
import { assertSafePublicUrl } from './security.js';

async function mark(workspaceId,signalId,channel,status,error=null){await query('INSERT INTO notifications (id,workspace_id,signal_id,channel,status,error,sent_at) VALUES ($1,$2,$3,$4,$5,$6,CASE WHEN $5=$7 THEN now() ELSE NULL END)',[id('ntf'),workspaceId,signalId,channel,status,error,'sent']);}

async function sendEmail(to,subject,html){if(!process.env.RESEND_API_KEY||!process.env.RADAR_FROM_EMAIL)throw new Error('Resend is not configured');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.RESEND_API_KEY}`},body:JSON.stringify({from:process.env.RADAR_FROM_EMAIL,to:[to],subject,html})});if(!r.ok)throw new Error(`Resend ${r.status}: ${(await r.text()).slice(0,200)}`);}
async function postWebhook(url,payload){const safe=await assertSafePublicUrl(url);if(safe.protocol!=='https:')throw new Error('Webhook must use HTTPS');const r=await fetch(safe,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Webhook ${r.status}`);}
async function sendWhatsApp(to,message){if(!process.env.WHATSAPP_ACCESS_TOKEN||!process.env.WHATSAPP_PHONE_NUMBER_ID)throw new Error('WhatsApp Cloud API is not configured');const r=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_GRAPH_VERSION||'v23.0'}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:message}})});if(!r.ok)throw new Error(`WhatsApp ${r.status}: ${(await r.text()).slice(0,200)}`);}

export async function dispatchSignalAlerts(signalId){const signal=(await query(`SELECT s.*,c.name company_name FROM signals s JOIN companies c ON c.id=s.company_id WHERE s.id=$1`,[signalId])).rows[0];if(!signal)return;const rules=(await query('SELECT * FROM alert_rules WHERE workspace_id=$1 AND enabled=true AND min_importance<=$2',[signal.workspace_id,signal.importance])).rows;const integrations=(await query('SELECT * FROM integrations WHERE workspace_id=$1',[signal.workspace_id])).rows;const owner=(await query(`SELECT u.email FROM users u JOIN workspace_members wm ON wm.user_id=u.id WHERE wm.workspace_id=$1 AND wm.role='owner' LIMIT 1`,[signal.workspace_id])).rows[0];for(const rule of rules){const categories=rule.categories||[];if(categories.length&&!categories.includes(signal.category))continue;for(const channel of rule.channels||['in_app']){try{if(channel==='in_app'){await mark(signal.workspace_id,signal.id,'in_app','sent');continue;}if(channel==='email'){await sendEmail(owner.email,`RADAR: ${signal.title}`,`<h2>${escapeHtml(signal.title)}</h2><p>${escapeHtml(signal.summary)}</p><p><b>Impact:</b> ${signal.importance}/100 · <b>Confidence:</b> ${signal.confidence}/100</p><p>${escapeHtml(signal.suggested_action||'Review this signal in RADAR.')}</p>`);}else if(channel==='slack'||channel==='teams'||channel==='webhook'){const targets=integrations.filter(i=>i.type===channel);if(!targets.length)throw new Error(`${channel} integration is not configured`);for(const target of targets)await postWebhook(unseal(target.secret_value),{text:`RADAR · ${signal.company_name}: ${signal.title}\n${signal.summary}\nImpact ${signal.importance} · Confidence ${signal.confidence}`,signal});}else if(channel==='whatsapp'){const targets=integrations.filter(i=>i.type==='whatsapp');if(!targets.length)throw new Error('WhatsApp target is not configured');for(const target of targets)await sendWhatsApp(unseal(target.secret_value),`RADAR · ${signal.company_name}\n${signal.title}\n${signal.summary}\nImpact ${signal.importance}/100`);}await mark(signal.workspace_id,signal.id,channel,'sent');}catch(error){await mark(signal.workspace_id,signal.id,channel,'failed',error.message.slice(0,300)).catch(()=>{});}}}}

function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

export async function sendBriefingEmail(workspaceId,briefing){if(!process.env.RESEND_API_KEY||!process.env.RADAR_FROM_EMAIL)return false;const owner=(await query(`SELECT u.email FROM users u JOIN workspace_members wm ON wm.user_id=u.id WHERE wm.workspace_id=$1 AND wm.role='owner' LIMIT 1`,[workspaceId])).rows[0];if(!owner)return false;await sendEmail(owner.email,`RADAR · ${briefing.title}`,`<h1>${escapeHtml(briefing.title)}</h1><div style="white-space:pre-wrap;line-height:1.6">${escapeHtml(briefing.content)}</div>`);return true;}
