import crypto from 'node:crypto';
import { query, transaction } from './db.js';
import { id } from './ids.js';

function norm(value){return String(value||'').trim().toLowerCase().replace(/\s+/g,' ').slice(0,240)}
function list(v){return Array.isArray(v)?v:[]}
function stableEntityId(type,label){return `ent_${crypto.createHash('sha1').update(`${type}:${norm(label)}`).digest('hex').slice(0,20)}`}

async function upsertTarget(client,workspaceId,type,label,priority,reason,entityId=null){const key=norm(label);if(!key)return;await client.query(`INSERT INTO watch_targets(id,workspace_id,target_type,label,normalized_key,entity_id,priority,reason,discovered_by)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,'company_brain')
ON CONFLICT(workspace_id,target_type,normalized_key) DO UPDATE SET priority=GREATEST(watch_targets.priority,EXCLUDED.priority),reason=COALESCE(EXCLUDED.reason,watch_targets.reason),entity_id=COALESCE(watch_targets.entity_id,EXCLUDED.entity_id),active=true,updated_at=now()`,[id('wat'),workspaceId,type,String(label).slice(0,240),key,entityId,priority,reason])}
async function upsertEntity(client,type,label,url=null,metadata={}){const entityId=stableEntityId(type,label);await client.query(`INSERT INTO entities(id,canonical_name,entity_type,canonical_url,metadata) VALUES($1,$2,$3,$4,$5::jsonb)
ON CONFLICT(id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name,canonical_url=COALESCE(EXCLUDED.canonical_url,entities.canonical_url),metadata=entities.metadata||EXCLUDED.metadata,updated_at=now()`,[entityId,String(label).slice(0,240),type,url,JSON.stringify(metadata)]);return entityId}

export async function syncWatchGraph(workspaceId){const primary=(await query(`SELECT c.*,cp.* FROM companies c LEFT JOIN company_profiles cp ON cp.company_id=c.id WHERE c.workspace_id=$1 AND c.is_primary=true LIMIT 1`,[workspaceId])).rows[0];if(!primary)return{targets:0};const competitors=(await query(`SELECT c.id,c.name,c.website,c.classification,r.threat,r.similarity FROM companies c LEFT JOIN relationships r ON r.target_company_id=c.id AND r.workspace_id=c.workspace_id WHERE c.workspace_id=$1 AND c.is_primary=false AND c.status IN ('active','candidate') ORDER BY COALESCE(r.threat,0) DESC LIMIT 100`,[workspaceId])).rows;let count=0;await transaction(async client=>{const selfEntity=await upsertEntity(client,'company',primary.name,primary.website,{company_id:primary.id,primary:true});await upsertTarget(client,workspaceId,'company',primary.name,100,'Your company',selfEntity);count++;for(const comp of competitors){const entity=await upsertEntity(client,'company',comp.name,comp.website,{company_id:comp.id,classification:comp.classification});const priority=Math.max(55,Math.min(100,Number(comp.threat||comp.similarity||60)));await upsertTarget(client,workspaceId,'company',comp.name,priority,`${comp.classification||'competitor'} company`,entity);count++;await client.query(`INSERT INTO entity_relationships(id,workspace_id,source_entity_id,relation_type,target_entity_id,confidence,metadata) VALUES($1,$2,$3,'COMPETES_WITH',$4,$5,$6::jsonb) ON CONFLICT(workspace_id,source_entity_id,relation_type,target_entity_id) DO UPDATE SET confidence=EXCLUDED.confidence,metadata=EXCLUDED.metadata`,[id('rel'),workspaceId,selfEntity,entity,Math.max(50,Number(comp.similarity||60)),JSON.stringify({classification:comp.classification})])}const buckets=[['market',[primary.industry,primary.subcategory],85,'Company market/category'],['customer_segment',list(primary.target_customers),82,'Target customer'],['product',list(primary.products),78,'Core product'],['technology',list(primary.technologies),70,'Relevant technology'],['geography',list(primary.geography),78,'Operating geography'],['topic',[...list(primary.features),primary.problem_use_case,primary.positioning].filter(Boolean),66,'Strategic topic']];for(const[type,values,priority,reason]of buckets){for(const value of values.flat().filter(Boolean).slice(0,40)){const entity=await upsertEntity(client,type,value,null,{});await upsertTarget(client,workspaceId,type,value,priority,reason,entity);count++;await client.query(`INSERT INTO entity_relationships(id,workspace_id,source_entity_id,relation_type,target_entity_id,confidence) VALUES($1,$2,$3,'WATCHES',$4,80) ON CONFLICT(workspace_id,source_entity_id,relation_type,target_entity_id) DO NOTHING`,[id('rel'),workspaceId,selfEntity,entity])}}});return{targets:count}}

export async function getWatchGraph(workspaceId){const[targets,rels]=await Promise.all([query(`SELECT wt.*,e.canonical_url,e.metadata FROM watch_targets wt LEFT JOIN entities e ON e.id=wt.entity_id WHERE wt.workspace_id=$1 AND wt.active=true ORDER BY wt.priority DESC,wt.created_at ASC`,[workspaceId]),query(`SELECT er.*,s.canonical_name source_name,s.entity_type source_type,t.canonical_name target_name,t.entity_type target_type FROM entity_relationships er JOIN entities s ON s.id=er.source_entity_id JOIN entities t ON t.id=er.target_entity_id WHERE er.workspace_id=$1 ORDER BY er.confidence DESC LIMIT 300`,[workspaceId])]);return{targets:targets.rows,relationships:rels.rows}}
