import { NextResponse } from 'next/server';
import { getCurrentUser,getWorkspaceForUser } from '@/lib/auth';
import { query } from '@/lib/db';
import { id } from '@/lib/ids';
import { assertSafePublicUrl,normalizeUrl } from '@/lib/security';
import { discoverCompetitorSources } from '@/lib/intelligence';
export const maxDuration=180;
export async function POST(request){try{const user=await getCurrentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const workspace=await getWorkspaceForUser(user.id);const b=await request.json();const safe=await assertSafePublicUrl(b.website);const url=normalizeUrl(safe.toString());const domain=url.hostname.replace(/^www\./,'');const name=String(b.name||domain).trim().slice(0,180);const classification=String(b.classification||'watchlist');const allowed=['direct','adjacent','substitute','emerging_threat','incumbent','watchlist'];if(!allowed.includes(classification))return NextResponse.json({error:'Invalid classification'},{status:400});const primary=(await query('SELECT id FROM companies WHERE workspace_id=$1 AND is_primary=true LIMIT 1',[workspace.id])).rows[0];const companyId=id('cmp');await query(`INSERT INTO companies (id,workspace_id,name,domain,website,is_primary,classification,status,approved_at) VALUES ($1,$2,$3,$4,$5,false,$6,'active',now()) ON CONFLICT DO NOTHING`,[companyId,workspace.id,name,domain,url.toString(),classification]);const actual=(await query('SELECT id FROM companies WHERE workspace_id=$1 AND domain=$2 ORDER BY created_at ASC LIMIT 1',[workspace.id,domain])).rows[0];if(!actual)return NextResponse.json({error:'Could not add company'},{status:500});await query(`INSERT INTO relationships (id,workspace_id,source_company_id,target_company_id,relationship_type,status,similarity,threat,confidence,rationale) VALUES ($1,$2,$3,$4,$5,'approved',0,0,100,'Manually added by workspace user') ON CONFLICT(workspace_id,source_company_id,target_company_id) DO UPDATE SET status='approved',relationship_type=EXCLUDED.relationship_type,updated_at=now()`,[id('rel'),workspace.id,primary.id,actual.id,classification]);await discoverCompetitorSources(workspace.id,actual.id);return NextResponse.json({ok:true,companyId:actual.id});}catch(error){return NextResponse.json({error:error.message},{status:400});}}
export async function DELETE(request){try{const user=await getCurrentUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const workspace=await getWorkspaceForUser(user.id);const companyId=new URL(request.url).searchParams.get('id');const c=(await query('SELECT is_primary FROM companies WHERE id=$1 AND workspace_id=$2',[companyId,workspace.id])).rows[0];if(!c)return NextResponse.json({error:'Company not found'},{status:404});if(c.is_primary)return NextResponse.json({error:'Primary company cannot be removed'},{status:400});await query('DELETE FROM companies WHERE id=$1 AND workspace_id=$2',[companyId,workspace.id]);return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error.message},{status:500});}}
