import http from 'node:http';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import { query } from '../lib/db.js';
import { claimJob, completeJob, failJob, pruneJobs } from '../lib/queue.js';
import { processJob, scheduleRecurringJobs } from '../lib/jobs.js';
import { runMonitoringBatch } from '../lib/monitor.js';

const workerId=`${os.hostname()}-${process.pid}-${randomUUID().slice(0,8)}`;
const idleMs=Math.max(500,Number(process.env.WORKER_IDLE_MS||1500));
const heartbeatMs=30000;
let lastHeartbeat=0,lastSchedule=0,lastMonitor=0,lastCleanup=0,lastProcessedAt=null,lastLoopError=null;
async function heartbeat(status='healthy'){await query(`INSERT INTO service_heartbeats(service,status,instance_id,last_seen_at,metadata) VALUES('radar-worker',$1,$2,now(),$3::jsonb) ON CONFLICT(service) DO UPDATE SET status=EXCLUDED.status,instance_id=EXCLUDED.instance_id,last_seen_at=now(),metadata=EXCLUDED.metadata`,[status,workerId,JSON.stringify({lastProcessedAt,lastLoopError,embedded:process.env.RADAR_EMBEDDED_WORKER==='true'})])}
if(process.env.RADAR_EMBEDDED_WORKER!=='true'){const port=Number(process.env.WORKER_HEALTH_PORT||process.env.PORT||10000);http.createServer(async(req,res)=>{if(req.url!=='/'&&req.url!=='/health'){res.writeHead(404,{'content-type':'application/json'});return res.end(JSON.stringify({ok:false,error:'not_found'}))}let database=false;try{await query('SELECT 1');database=true}catch{}const body={ok:database,service:'radar-worker',database,workerId,lastProcessedAt,lastLoopError};res.writeHead(database?200:503,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body))}).listen(port,'0.0.0.0',()=>console.log(`[RADAR worker] health server on ${port}`))}
console.log(`[RADAR worker] durable processor starting as ${workerId}${process.env.RADAR_EMBEDDED_WORKER==='true'?' (embedded)':''}`);
while(true){try{lastLoopError=null;const now=Date.now();if(now-lastHeartbeat>heartbeatMs){await heartbeat('healthy');lastHeartbeat=now}if(now-lastSchedule>60000){await scheduleRecurringJobs().catch(e=>console.error('[RADAR scheduler]',e.message));lastSchedule=now}if(now-lastMonitor>120000){await runMonitoringBatch(Number(process.env.MONITOR_BATCH_SIZE||20)).catch(e=>console.error('[RADAR sensors]',e.message));lastMonitor=now}if(now-lastCleanup>6*3600000){await pruneJobs().catch(()=>{});lastCleanup=now}const job=await claimJob(workerId);if(!job){await new Promise(r=>setTimeout(r,idleMs));continue}const started=Date.now();let status='completed',errorText=null;try{const result=await processJob(job);await completeJob(job.id);lastProcessedAt=new Date().toISOString();console.log(`[RADAR worker] ${job.queue_name}#${job.id} completed`,JSON.stringify(result||{}).slice(0,1200))}catch(error){status='failed';errorText=error?.message||String(error);await failJob(job,errorText);console.error(`[RADAR worker] ${job.queue_name}#${job.id} failed`,error)}finally{const payload=typeof job.payload==='string'?JSON.parse(job.payload):job.payload||{};await query(`INSERT INTO job_runs(queue_name,message_id,job_type,workspace_id,status,duration_ms,error) VALUES($1,$2,$3,$4,$5,$6,$7)`,[job.queue_name,job.id,payload.type||'unknown',payload.workspaceId||null,status,Date.now()-started,errorText?.slice(0,1000)||null]).catch(()=>{})}}catch(error){lastLoopError=error?.message||String(error);console.error('[RADAR worker] loop error',error);await heartbeat('degraded').catch(()=>{});await new Promise(r=>setTimeout(r,Math.max(3000,idleMs)))}}
